### ISSUE TITLE
Photo addition?

### ISSUE THREAD

**Issue by Appaljack** [toopriddy/mytime#282]
Wondering how much it would take to add a photo section? Would be nice to add pic of person's house or even themselves though this can be partly done in contacts. Would like pub list to be in harmony with current reporting requirements (US), that is brochures combined with all that is reportable as a brochure though this may change from time to time. And I loved this app with the mapping capability. Would be nice to pull zip code, too, but I know that wpuld probably be prohibitive in resources and mostly for rural areas.

**Comment by toopriddy** [comment]
Thank you for the comments.  

I have the picture feature on the feature request list on the MyTime website http://priddysoftware.com/home/support/feature-request-list 

The publication list does need to be worked through, it has not been filtered out because of historical data from years past.  MyTime live calculates information from the data.

I have not historically worried about zip code (no one has requested this in 8 years).  I would be interested in the use case that you are solving with this.

Please email your replies to toopriddy@gmail.com  This issue list is for bugs only, I discuss feature requests over email normally.
