### ISSUE TITLE
Combining placements

### ISSUE THREAD

**Issue by yeprahs** [toopriddy/mytime#295]
I believe we need to send the total of mags, tracts, video pres, this app now sends the collective amount so I now have to manually put all them outs in. Any chance this can be fixed?

**Comment by toopriddy** [comment]
hello @yeprahs, since Jan 1, 2016 we are supposed to combine all magazine, brochure, tracts, handbills, etc as "Placements".  We are not to send in the seperated mags, tracts etc to the secretary.  This change was as far as I knew a global changes since the S-4 forms changed for everyone.

MyTime is following the direction given to us late last year for this workflow change.  MyTime still lets you count them separately and set goals on them separately but it combines them appropriately based on the rules for submitting your information.

FYI: videos shown is separate from placements and do not count within your placements.

I hope this helps (I will be closing this issue report as not-a-bug but you can reply back or directly email me at toopriddy@gmail.com for further clarification)
