### ISSUE TITLE
App won't open on iOS 9.3.2

### ISSUE THREAD

**Issue by fapruitt** [toopriddy/mytime#298]
Hi, the My Time app updated to the latest version and now it crashes each time I go to open it. I'm running iOS 9.3.2. I can't access any of my return visits or time info. Thanks!

**Comment by kellisima** [comment]
Me too - exactly the same issue.  And I'm supposed to take the CO on my calls tomorrow afternoon!!  EEEEEEK, please help!!

**Comment by toopriddy** [comment]
I am sorry for the trouble. Please go to the Settings app-> then scroll down and tap on MyTime. Then turn on the instant email backup. Now try to open MyTime. Send me the email backup and I will try to see what is going on. 

You can also let me know what device you are using as well

Again sorry for the trouble

**Comment by kellisima** [comment]
Thanks!!  No need to apologize - I love this app and I know it's just a temporary glitch ☺️
I have a 6S+  / I'm attaching a screenshot that has my phone deets if that helps.  I'll email you the backup in a sec. 

Thanks so much!
Kelly

**Comment by cossa82** [comment]
Hi.. Has this been resolved yet. I too have the same issue.. Looks like it's loads but then cuts out. It's only after I updates to the new my time update released on 5th June?? Please help

**Comment by toopriddy** [comment]
I have just fixed this in the development version.  It turns out it is a data processing issue when first starting up when converting the original RBC to LDC and then merging your LDC created category into the old RBC.  I can fix your data and send back to you to get things back working again.  Please email your backup file to toopriddy@gmail.com and note in the beginning of the email to fix your crashing issue.  

I am sorry for the trouble, we just hit an edge case that the beta tests did not catch :(

**Comment by TerencedeHoog** [comment]
I’m having trouble with opening the settings. If i want to change something in setting the app shuts down. I realy like the app and its a great help working on the country side and have now streetnames😜 Terence.

**Comment by toopriddy** [comment]
Sorry for the trouble

Please let me know
1. what iOS version you are using
2. is your device Jailbroken
3. is there an update for MyTime on the AppStore?
