### ISSUE TITLE
Incorrect Return Visit counts

### ISSUE THREAD

**Issue by stephen-au** [toopriddy/mytime#307]
Greetings!

I've noticed an issue with the current version of MyTime where by the Return Visit count does not tally at all to the monthly totals. When selecting the call type "Return Visit" against a call, the Type doesn't appear against the call after saving it. If you Edit the call, it shows the "Return Visit" having been selected.

**Comment by toopriddy** [comment]
Hello Stephen, Please send me your email backup by going to
MyTime->More->Settings->Email Backup->Email MyTime Backup to
toopriddy@gmail.com and let me know what you are talking about in your
email.

I am unable to reproduce the situation you mentioned in your email. If you
are not editing the call the "return visit" type is hidden from you since
it is the default so that it does not clutter up the screen.  when you
press edit, then the return visit line appears so that you can change it.
This is normal behavior.

I am interested though in what you are saying that it is not tallying the
information. I have not been able to reproduce this and have not seen any
reports from other users about this.

**Comment by stephen-au** [comment]
Hi Brent, thanks for your reply and clarification. It looks like the current month is tallying correct. I'll close this case for now, but will reopen it if required. Thanks for your good work.
