### ISSUE TITLE
Doelstelling

### ISSUE THREAD

**Issue by lotus658** [toopriddy/mytime#315]
De rode zin onder het aantal uren klopt niet.
Ik ben deze maand nog hulppionier en heb 33 uur gewerkt. Er staat nu een doe,stelling van 50 uur. Dat moet dus 17 uur zijn.
Ook de uren van februari kloppen niet.

**Comment by toopriddy** [comment]
Hello, If you need to you can go to translate.google.com to translate this
message.

MyTime calculates the goal based on the average hours you need to get in
the next months to be able to reach the yearly goal.  The monthly goal is
not a strict 70 hours but rather a monthly average that can get you to 840
hours for the year.  Say for instance you do not meet your 70 hours a month
goal for the first several months, then your monthly average hours to reach
your 840 goal will have to be more than 70 hours a month.  The same happens
when you get more than 70 hours a month for the past months, your average
monthly goal will decrease below 70 hours a month since you will not have
to achieve 70 hours in the upcoming months to achieve the 840 goal.

If the above information does not help. please send me a detailed email
with what you have seen and what you expect to see.  Email me directly at
toopriddy@gmail.com

**Comment by lotus658** [comment]
Hi,
Problem solved. Got an iPhone 6s plus from my husband because I'm gonna be a regular Pioneer again and downloaded the app on my new cellphone.
Thnx for reacting.
Greetings, Loïs Terpstra
________________________________
Van: toopriddy <notifications@github.com>
Verzonden: dinsdag 21 maart 2017 03:38:58
Aan: toopriddy/mytime
CC: lotus658; State change
Onderwerp: Re: [toopriddy/mytime] Doelstelling (#315)

Hello, If you need to you can go to translate.google.com to translate this
message.

MyTime calculates the goal based on the average hours you need to get in
the next months to be able to reach the yearly goal. The monthly goal is
not a strict 70 hours but rather a monthly average that can get you to 840
hours for the year. Say for instance you do not meet your 70 hours a month
goal for the first several months, then your monthly average hours to reach
your 840 goal will have to be more than 70 hours a month. The same happens
when you get more than 70 hours a month for the past months, your average
monthly goal will decrease below 70 hours a month since you will not have
to achieve 70 hours in the upcoming months to achieve the 840 goal.

If the above information does not help. please send me a detailed email
with what you have seen and what you expect to see. Email me directly at
toopriddy@gmail.com

**Comment by toopriddy** [comment]
Thank you for following up
