### ISSUE TITLE
Sync to multiple devices?

### ISSUE THREAD

**Issue by MagboneD** [toopriddy/mytime#344]
Any chance you will include a feature to automatically sync across devices? I understand you want to keep an os independent backup method, but I find I often lose synchronization because I don’t have the correct device with me when I make a call. The manual web server feature is somewhat cumbersome

**Comment by toopriddy** [comment]
Sorry for the trouble, only recently did CoreData become stable enough for me to start trusting it with call data.  This will take a long time to implement and work out the bugs it will cause.  Currently iCloud backup is probably the quickest way to sync between devices.  Go to MyTime->More->Settings-> Backup->and then tap on iCloud to have it checked.  if you want an immediate sync tap on the "save backup now" and then on the other device you can restore from that backup which should be top of the list of backed up items in MyTime->More->Settings-> Backup

Since this is a feature request I will close this issue (this is on the feature request list on the MyTime website http://priddysoftware.com/home/support/feature-request-list  )
