### ISSUE TITLE
Remaining hours for month not correct

### ISSUE THREAD

**Issue by cfehlauer** [toopriddy/mytime#348]
I have 10 hours 30 minutes - all regular hours, no LDC or anything.  Then it says Need 55 hours 6 minutes for goal.  
All of my previous months this year have LDC or DRC time.  But I record everything in increments of 15 minutes so this doesn't make sense.

**Comment by toopriddy** [comment]
Hello, I am sorry for the confusion.  MyTime calculates your monthly average needed to achieve the pioneer Yearly goal.  If you end up getting more hours in the previous months than 70 then the average number of hours you need to meet the yearly goal will be less than 70 hours each month.  Conversly if you were not able to do 70 hours in previous months then the average monthly hours you will need to achieve to meet the yearly 840 hours goal will end up being more than 70 hours per month.

MyTime calculates the average monthly hours for you so that you do not have to and helps keep you on track.  MyTime takes into account LDC time or other pioneer credits and adds them based on the branch instructions.

I hope this helps

**Comment by cfehlauer** [comment]
Ok. Thanks. According to my math it’s still not correct because I can’t carry over Ldc time. 

Thank you. 
Chelsea

**Comment by toopriddy** [comment]
Hello Chelsea, please email me directly (not replying to this public site)
your backup by going to MyTime->More->Settings->Email Backup->Email MyTime
Backup to toopriddy@gmail.com
 and I can take a look.  Most of the time people do not realize the
instructions of how we are supposed to handle credits.

LDC hours can only assist up to 70 hours for the month, for instance if you
have 40 field service hours and 60 LDC hours, you only get to count 30 of
the LDC credits for that month only and do not get to cary them over.
MyTime will indicate this with a note right under this in your service year
information.  If you are a special pioneer the rules are different. and
also if you are a remote Bethelite then the rules are a little different as
well (but you would know them anyways because you would have to train your
secretary about the differences :)
Make sure that the default behavior for LDC hours has not been changed, go
to the "Hours" tab, then tap on the top "hours" word and select "Edit" and
then tap on "LDC" and make sure that the affects pioneer hours switch is ON
and make sure the other "Direct Credit" switch is "OFF" (for instance
pioneer school is a direct credit, but not LDC).

If your pioneer start date is in this service year (go to
MyTime->More->Settings->Pioneer Start Date to change) then the calculations
take into account your prorated yearly goals based on your pioneer start
date.

If you have changed the goals in MyTime->More->Settings-> Goals to "custom"
then it would affect how goals are calculated for you.  99% of the time
pioneers appreciate the default rules and calculations.

I hope this helps, if not then I would be happy to take a look at the data
and do the math to see where the problem might be.
