### ISSUE TITLE
Pins not being added to map view on new calls added

### ISSUE THREAD

**Issue by reubenaw** [toopriddy/mytime#354]
Hello. I just noticed that my time isn’t adding pins to the map you after the last update for any new calls I’m entering. I’ve never noticed this before so I’m guessing it’s a bug that’s just being introduced. Please advise. Many thanks. Reuben

**Comment by toopriddy** [comment]
Hello Reuben, sorry for the trouble.  MyTime relies on google maps
reverse-geocoding and it looks like their service has been down.  I will
look into this, the last time this happened it was resolved in around 24
hours.  It looks like I might just have to go ahead and convert over to
apple's reverse-geocoding service instead of google's since it has been so
unstable in the last few months.

I am sorry for the trouble.  Either this will resolve itself soon or I will
have to change MyTime to have things be more stable (this has not been an
issue since 2007 and for some reason I have had only issues this year with
Google's service being flakey.

**Comment by reubenaw** [comment]
Hello Brent

Thanks for your reply and the insight. I’m sure that must be frustrating :(  

Thanks for your help on this!

Reuben 
416-910-3400
reubenweigand@gmail.com

**Comment by toopriddy** [comment]
Apple just approved this update a few minutes ago.  Please upgrade MyTime
and try again.

I hope this helps

**Comment by reubenaw** [comment]
Hello Brent. 

I tried the update. At first the latest addresses added over the last few days since the previous update still didn’t show up so I tried deleting just the address on those calls and then re-adding the addresses - it worked!  Thanks very much for the fix. (If anyone else experienced this problem, deleting just the address, saving the deletion and the re-entering the address seems to work.)

Wonderful program my brother!

Best regards,

Reuben 
416-910-3400
reubenweigand@gmail.com
