### ISSUE TITLE
Informatiin is stuck

### ISSUE THREAD

**Issue by xyzstreets** [toopriddy/mytime#360]
When adding a new address, note of any kind. The informatiin of the last entered note/address is still shown. It is a bit confusing.

**Comment by toopriddy** [comment]
Hello, sorry for the confusion. MyTime remembers the last street and city and state for the cases when you are working door to door and get a door on the same street and helps you by not requiring you to type in all of the address info each time. 

Many publishers do not have network connections to tap on the “automatically lookup address” for whatever reason and this helps them focus on the ministry instead of lots of typing. 

Regarding the notes, you have a history of the notes you have typed in so that if you reuse the same conversation or article, you can also start with some common notes and modify as appropriate. This will help to reduce typing and focus on the ministry. If you are not wanting this feature you can go to MyTime->More->Settings-> show the last X notes -> and change this to 0 to not show them. 

I hope this helps
